[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling", ]

[project]
name = "tomah"
version = "0.0.0"
requires-python = ">=3.8"

dependencies = [
  "requests>=2.28.1",
  "json-api-doc>=0.15.0",
]

[tool.black]
line-length = 120
